version: "3.9"

services:
  db:
    image: postgres:16
    container_name: calories_postgres
    restart: always
    environment:
      POSTGRES_USER: calories_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: calories_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: